---
- hosts: server2
  user: root
  gather_facts: yes
  tasks:
    - name: httpd installation
      yum:  name=httpd state=installed
    - name: httpd start
      service: name=httpd state=started
    - name: copy index file
      copy: src=index.html dest=/var/www/html/index.html
      notify: restart httpd
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted 
